### ISSUE TITLE
EVPN advertise subnet error

### ISSUE THREAD

**Issue by MoOyeg** [Orange-OpenSource/bagpipe-bgp#11]
Hello
Does Bagpipe support the advertise subnet function for evpn.
When trying to test I get the following error:

sudo bagpipe-rest-attach  --attach --port netns --ip 2.2.2.2 --network-type evpn --vpn-instance-id green --rt 64512:100 --gateway-ip 2.2.2.1 --advertise-subnet true
Will plug local namespace green into network
[WARNI]  Exit code 1 when running 'ip netns add green': Cannot create namespace file "/var/run/netns/green": File exists
[WARNI]  Exit code 1 when running 'ip link delete tons-green': Cannot find device "tons-green"
Local port: tons-green (56:bb:16:fd:32:7f)
request: {"import_rt": ["64512:100"], "gateway_ip": "2.2.2.1", "export_rt": ["64512:100"], "local_port": {"linuxif": "tons-green"}, "advertise_subnet": true, "vpn_type": "evpn", "ip_address": "2.2.2.2/24", "mac_address": "56:bb:16:fd:32:7f", "vpn_instance_id": "green", "readvertise": null}
   Server Error
error 500, reason: Internal Server Error

And see the following error in the looking-glass logs:
{

```
"message": "None\n",
"time": "2016-10-04 14:42:05,768",
"name": "bagpipe.bgp.rest_api",
"level": "ERROR"
```

},
{

```
"message": "Bottle catched an error: None",
"time": "2016-10-04 14:42:05,768",
"name": "bagpipe.bgp.rest_api",
"level": "ERROR"
```

},
{

```
"message": "attach_localport: An error occurred during local port plug to VPN: ",
"time": "2016-10-04 14:42:05,766",
"name": "bagpipe.bgp.rest_api",
"level": "ERROR"
```

},
{

```
"message": "Error in vifPlugged: ",
"time": "2016-10-04 14:42:05,766",
"name": "bagpipe.bgp.vpn.evpn.1",
"level": "ERROR"
```

},

**Comment by tmmorin** [comment]
Hi,

No, indeed the advertise subnet options is meant to be used with ipvpn.
The error you see is because there is no code yet to properly catch the use of the option with evpn :-(

ExaBGP code, where route encoding/decoding is done, has support for E-VPN prefix advertisement; we could possibly reuse that to support draft-ietf-bess-evpn-prefix-advertisement, but some work would be required.

**Comment by MoOyeg** [comment]
Thanks So much for quick response.
