### ISSUE TITLE
Remnants of a merge conflict in rest_attach.py

### ISSUE THREAD

**Issue by lukehinds** [Orange-OpenSource/bagpipe-bgp#13]
A leftover merge conflict pointer (<<<<<<< HEAD) can seen on lines 291 - 297

https://github.com/Orange-OpenSource/bagpipe-bgp/blob/master/bagpipe/bgp/cli/rest_attach.py#L291

I have not made a push, as I am not sure which code is better to keep.

**Comment by tmmorin** [comment]
Thanks Luke!
