### ISSUE TITLE
"Exception: label.bottomOfStack should not be set" on PMSI tunnel attribute parsing, with RTC disabled

### ISSUE THREAD

**Issue by fxpester** [Orange-OpenSource/bagpipe-bgp#7]
just installed bagpipe-bgp, tried to peer, got error:  
`2016-06-01 05:45:46,030 BGP-192.168.1.18:receiveLoop   bagpipe.bgp.engine.exabgp_peer_worker.192-168-1-18 ERROR    Error while reading BGP message: label.bottomOfStack should not be set
2016-06-01 05:45:46,031 BGP-192.168.1.18:receiveLoop   bagpipe.bgp.engine.exabgp_peer_worker.192-168-1-18 ERROR    Error: label.bottomOfStack should not be set (=> aborting receiveLoop and reinitializing)
2016-06-01 05:45:46,034 BGP-192.168.1.18:receiveLoop   bagpipe.bgp.engine.exabgp_peer_worker.192-168-1-18 WARNING  Traceback (most recent call last):
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/bgp/engine/bgp_peer_worker.py', line 256, in _receiveLoop
    loopResult = self._receiveLoopFun()
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/bgp/engine/exabgp_peer_worker.py', line 269, in _receiveLoopFun
    message = self.protocol.read_message()
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 176, in read_message
    update = self.UpdateFactory(data)
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 487, in UpdateFactory
    attributes = self.AttributesFactory(attribute)
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 509, in AttributesFactory
    return self._AttributesFactory(data).attributes
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 612, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 636, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 641, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 646, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 619, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 673, in _AttributesFactory
    return self._AttributesFactory(data[length:])
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/network/protocol.py', line 650, in _AttributesFactory
    self.attributes.add(PMSITunnel.unpack(data[:length]))
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/message/update/attribute/pmsi_tunnel.py', line 131, in unpack
    return tunnel_types_to_class[subtype].unpack(label,flags,data)
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/message/update/attribute/pmsi_tunnel.py', line 161, in unpack
    return PMSITunnelIngressReplication(ip,label,flags)
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/message/update/attribute/pmsi_tunnel.py', line 149, in __init__
    PMSITunnel.**init**(self, self.subtype, label, flags)
  File '/usr/local/lib/python2.7/dist-packages/bagpipe/exabgp/message/update/attribute/pmsi_tunnel.py', line 74, in **init**
    if label.bottomOfStack: raise Exception('label.bottomOfStack should not be set')
Exception: label.bottomOfStack should not be set

2016-06-01 05:45:56,046 BGP-192.168.1.18               bagpipe.bgp.engine.exabgp_peer_worker.192-168-1-18 WARNING  Exception while initiating connection: The TCP connection is closed
2016-06-01 05:46:06,961 BGP-192.168.1.18               bagpipe.bgp.engine.exabgp_peer_worker.192-168-1-18 WARNING  Exception while initiating connection: The TCP connection is closed
`  
fixed by - apt-get install python-txtftp (with tons of depency packages)

**Comment by fxpester** [comment]
oops, command `apt-get install python-txtftp` fixed this error only in enable_rtc=True mode. if I switch to enable_rtc=False error - same error hits again.

**Comment by tmmorin** [comment]
hi @fxpester 

I couldn't see why txtftp would be involved, bagpipe-bgp makes no use of twisted. 

On RTC: with enable_rtc = True, bagpipe-bgp will receive only routes that it specifically asks for (routes carrying RT X, RT Y , ...), with enable_rtc=False, its peer will send everyting.

So, maybe the peer has one route which formats the PMSI Tunnel attribute with the bottom bit set for the label. 

Can you tell more about which BGP stack you are trying to peer ?
Can you send a pcap trace or the exchange (port 179) ?

**Comment by tmmorin** [comment]
You can comment line 74 of bagpipe/exabgp/message/update/attribute/pmsi_tunnel.py .
That should solve your issue, if confirmed I'll push the fix.

**Comment by fxpester** [comment]
thanks you tmmorin, commenting line 74 out works well. Do you still want packet dump or looking glass ? I can mail it to you (not at irc right now).

**Comment by tmmorin** [comment]
And don't really need the capture, since the problem is identified (I'll push the fix right now)
But I'm interested to know what E-VPN stack you are trying to peer with, and the results you get.
